export const MAKE_HISTORICAL_DATA_REQUEST = 'MAKE_HISTORICAL_DATA_REQUEST'
export const HISTORICAL_DATA_REQUEST_SUCCESS = 'HISTORICAL_DATA_REQUEST_SUCCESS'
export const HISTORICAL_DATA_REQUEST_FAILURE = 'HISTORICAL_DATA_REQUEST_FAILURE'

export const SUBSCRIBE_TO_DATA = 'SUBSCRIBE_TO_DATA'
export const SUBSCRIBE_TO_DATA_SUCCESS = 'SUBSCRIBE_TO_DATA_SUCCESS'

export const UN_SUBSCRIBE_TO_DATA = 'UN_SUBSCRIBE_TO_DATA'
export const UN_SUBSCRIBE_TO_DATA_SUCCESS = 'UN_SUBSCRIBE_TO_DATA_SUCCESS'